name: Build and release

on:
  workflow_dispatch:
    inputs:
      version_r:
        description: "R versions to build (36, 40, 41, 42, 43 valid; also 36,40,41,42,43 for all)"
      version_bioc: 
        description: "Bioconductor versions to build (3.16, 3.17, 3.18 valid; also 3.16,3.17,3.18 for all)"
      version_image:
        description: "Version of image (vx (e.g. v1) or dev valid)"
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Install apptainer
      run: .devcontainer/scripts/install-apptainer.sh

    - name: Build and release manually-selected versions of Rocker images
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Creating new images for manually-selected versions of Rocker images"
        set -e
        IFS=',' read -ra VERSIONS_RBIOC <<< "${{ github.event.inputs.version_r }}"
        for VERSION_RBIOC in "${VERSIONS_RBIOC[@]}"; do
          echo "Building version $VERSION_RBIOC"
          IFS=',' read -ra VERSIONS_IMAGE <<< "${{ github.event.inputs.version_image }}"
          for VERSION_IMAGE in "${VERSIONS_IMAGE[@]}"; do
            echo "Building version $VERSIONS_IMAGE"
            ./build_and_release.sh r "$VERSION_RBIOC" "$VERSION_IMAGE"
          done
        done
    - name: Build and release manually-selected versions of BioConductor images
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Creating new images for manually-selected versions of Rocker images"
        set -e
        IFS=',' read -ra VERSIONS_RBIOC <<< "${{ github.event.inputs.version_bioc }}"
        for VERSION_RBIOC in "${VERSIONS_RBIOC[@]}"; do
          echo "Building version $VERSION_RBIOC"
          IFS=',' read -ra VERSIONS_IMAGE <<< "${{ github.event.inputs.version_image }}"
          for VERSION_IMAGE in "${VERSIONS_IMAGE[@]}"; do
            echo "Building version $VERSIONS_IMAGE"
            ./build_and_release.sh bioc "$VERSION_RBIOC" "$VERSION_IMAGE"
          done
        done
