name: Build and release

on:
  push:
    branches: [ main ]
    paths:
      - 'src/def/36.def'
      - 'src/def/40.def'
      - 'src/def/41.def'
      - 'src/def/42.def'
      - 'src/def/43.def'
  workflow_dispatch:
    inputs:
      version:
        description: "R versions to build"
        required: true
        default: "36,40,41,42,43"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Install apptainer
      run: .devcontainer/scripts/install-apptainer.sh
    
    - name: Build and release manually-selected versions
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Creating new images for manually-selected versions"
        set -e
        IFS=',' read -ra VERSIONS <<< "${{ github.event.inputs.version }}"
        for VERSION in "${VERSIONS[@]}"; do
          echo "Building version $VERSION"
          ./build_and_release.sh $VERSION
        done
